---
title: "Biostat 203B Homework 4"
subtitle: Due ~~Mar 20~~ Mar 22 @ 11:59PM
output:
  # ioslides_presentation: default
  html_document:
    toc: true
    toc_depth: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Introduction


## Data Preparation

Load database libraries and the tidyverse frontend:
```{r}
library(DBI)
library(RPostgreSQL)
library(tidyverse)
library(dplyr)
library(lubridate)
library(ggplot2)
```

Credentials for using PostgreSQL database. We are going to use username `postgres` with password `postgres` to access the `mimic` database in the schemee `mimiciii`. 
```{r}
# Load configuration settings
dbdriver <- 'PostgreSQL'
user  <- 'postgres'
password <- 'postgres'
dbname <- 'mimic'
schema <- 'mimiciii'
# Connect to the database using the configuration settings
con <- dbConnect(RPostgreSQL::PostgreSQL(), 
                 dbname = dbname, 
                 #host = host, 
                 #port = port, 
                 user = user, 
                 password = password)
# Set the default schema
dbExecute(con, paste("SET search_path TO ", schema, sep=" "))
```

```{r}
tbl(con, "d_icd_diagnoses") %>%
  filter(str_detect(tolower(long_title), "tuberculo")) %>%
  print() -> tuber_codes
```

```{r}
tbl(con, "diagnoses_icd") %>%
  semi_join(tuber_codes, by = "icd9_code") %>%
  filter(seq_num <= 5) %>%
  group_by(subject_id, hadm_id) %>%
  filter(min_rank(seq_num) <= 1) %>%
  ungroup() %>%
  select(subject_id, hadm_id, icd9_code, seq_num) %>%
  print() -> study_admissions
```


```{r}
study_admissions %>%
  mutate(principal_dx = seq_num == 1) %>%
  select(-seq_num) %>%
  print() -> study_admissions
```

```{r}
tbl(con, "drgcodes") %>%
  filter(str_detect(drg_type, "APR")) %>%
  select(subject_id, hadm_id, drg_severity) %>%
  right_join(study_admissions, by = c("subject_id", "hadm_id")) %>%
  mutate(drg_severity = ifelse(is.na(drg_severity), 1, drg_severity)) %>%
  print() -> study_admissions
```

```{r}
study_admissions %>%
  left_join(
    select(tbl(con, "admissions"),
           subject_id, hadm_id, admittime, dischtime, hospital_expire_flag
    ), by = c("subject_id", "hadm_id")
  ) %>%
  filter(hospital_expire_flag == 0) %>% # patients who did not die in hospital
  select(-hospital_expire_flag) %>%
  left_join(
    select(tbl(con, "patients"), subject_id, dob, dod),
    by = "subject_id"
  ) %>%
  print(width = Inf) -> study_admissions
```

```{r}
study_admissions %>%
  mutate(tt_death = date_part("day", dod) - date_part("day", dischtime)) %>%
  mutate(mortality = ifelse(is.na(tt_death <= 30), FALSE, tt_death <= 30)) %>%
  mutate(age = date_part("year", admittime) - date_part("year", dob)) %>%
  filter(age < 90) %>%
  mutate(age = age - ifelse(
    date_part("month", admittime) < date_part("month", dob) |
      (
        date_part("month", admittime) == date_part("month", dob) &
          date_part("day", admittime) < date_part("day", dob)
      ),
    1,
    0
  )) %>%
  select(-admittime, -dischtime, -dob, -dod, -tt_death) %>%
  select(subject_id, hadm_id, age, mortality, everything()) %>%
  print() -> study_admissions
```

```{r}
tbl(con, "admissions") %>%
  select(subject_id, ethnicity) %>%
  distinct() %>%
  print() -> study_subjects
tbl(con, "patients") %>%
  select(subject_id, gender) %>%
  distinct() %>%
  full_join(study_subjects, by = "subject_id") %>%
  print() -> study_subjects
study_subjects %>%
  semi_join(study_admissions, by = "subject_id") %>%
  print() -> study_subjects
```

```{r}
unknown_ethnicity <- c(
  "OTHER",
  "UNABLE TO OBTAIN",
  "UNKNOWN/NOT SPECIFIED",
  "MULTI RACE ETHNICITY",
  "PATIENT DECLINED TO ANSWER",
  "UNKNOWN"
)

study_subjects %>%
  collect() %>%
  mutate(ethnic_group = case_when(
    str_detect(ethnicity, "^ASIAN") ~ "ASIAN",
    str_detect(ethnicity, "^BLACK") ~ "BLACK",
    str_detect(ethnicity, "^HISPANIC") ~ "HISPANIC",
    str_detect(ethnicity, "^WHITE") ~ "WHITE",
    ethnicity %in% unknown_ethnicity ~ NA_character_,
    TRUE ~ NA_character_
  )) %>%
  select(subject_id, gender, ethnic_group) %>%
  print() -> study_subjects
```

```{r}
most <- function(x) {
  if (all(is.na(x))) return(NA_character_)
  y <- table(x, useNA = "no")
  if (length(which(y == max(y))) > 1) return(NA_character_)
  return(names(y)[which.max(y)])
}

study_subjects %>%
  group_by(subject_id) %>%
  summarize(ethnic_group = most(ethnic_group)) %>%
  ungroup() %>%
  mutate(ethnic_group = ifelse(is.na(ethnic_group), "UNKNOWN", ethnic_group)) %>%
  print() -> subject_ethnic_groups

study_subjects %>%
  select(subject_id, gender) %>%
  left_join(subject_ethnic_groups, by = "subject_id") %>%
  print() -> study_subjects
```

```{r}
study_admissions %>%
  left_join(study_subjects, by = "subject_id", copy = TRUE) %>%
  print() -> study_admissions
```
```{r}
study_admissions %>%
  distinct(.keep_all = T) %>%
  print() -> study_admissions
```

## Data Visualization

```{r}
study_admissions %>% 
  collect() %>%
  distinct(subject_id, .keep_all = T) %>%
  ggplot(aes(x = age)) + 
  geom_histogram(bins = 100) +
  labs(x = "Age", title = "Distribution of Age among Patient")
```

```{r}
study_admissions %>% 
  collect() %>%
  distinct(subject_id, .keep_all = TRUE) %>%
  ggplot(mapping = aes(x = gender, 
                       fill = gender)) + 
  geom_bar() + 
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.x=element_blank()) +
  geom_text(stat = 'count', aes(label = ..count.., vjust = -0.2)) +
  labs(title = "Distribution of Gender among Patient")
```
```{r}
study_admissions %>% 
  collect() %>%
  distinct(subject_id, .keep_all = TRUE) %>%
  ggplot() +
  geom_bar(mapping = aes(x = ethnic_group, fill = ethnic_group)) +
  labs(x = "Ethnic Group", y = "Counts",
       title = "Distribution of Ethnicity among Patient")
```
```{r}
study_admissions %>% 
  collect() %>%
  distinct(subject_id, .keep_all = TRUE) %>%
  ggplot(mapping = aes(x = mortality, 
                       fill = mortality)) + 
  geom_bar() + 
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.x=element_blank()) +
  geom_text(stat = 'count', aes(label = ..count.., vjust = -0.2)) +
  labs(title = "Distribution of Mortality among Patient")
```
```{r}
study_admissions %>% 
  collect() %>%
  ggplot(mapping = aes(x = principal_dx, 
                       fill = principal_dx)) + 
  geom_bar() + 
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.x=element_blank()) +
  geom_text(stat = 'count', aes(label = ..count.., vjust = -0.2)) +
  labs(title = "Distribution of Principal Diagnose among Admissions")
```
```{r}
study_admissions %>% 
  collect() %>%
  ggplot(mapping = aes(x = drg_severity, 
                       fill = drg_severity)) + 
  geom_bar() + 
  labs(x = "Severity Level", y = "Counts",
    title = "Distribution of Severity Level among Admissions")
```

```{r}
study_admissions %>% 
  collect() %>%
  group_by(icd9_code) %>%
  summarise(counts = n()) %>%
  arrange(desc(counts)) %>%
  slice(2:11) %>%
  ggplot(., aes(x = icd9_code, y = counts)) + 
  geom_bar(stat = 'identity') + 
  labs(x = "Diagnostics Type",
       title = "Distribution of Diagnostics Type (Top 10)")
```

## Analytics
# Logistic Regression
```{r}
model <- glm(mortality ~ age + drg_severity + icd9_code
             + principal_dx + gender + ethnic_group, family = binomial,
             data = study_admissions)
summary(model)
```
# Neural Network
```{r}
library(keras)
model <- keras_model_sequential() 
model %>% 
  layer_dense(units = 256, activation = 'relu', input_shape = c(784)) %>% 
  layer_dropout(rate = 0.4) %>% 
  layer_dense(units = 128, activation = 'relu') %>%
  layer_dropout(rate = 0.3) %>%
  layer_dense(units = 10, activation = 'softmax')
summary(model)
model %>% compile(
  loss = 'categorical_crossentropy',
  optimizer = optimizer_rmsprop(),
  metrics = c('accuracy')
)
history <- model %>% fit(
  study_admissions, 
  epochs = 30, batch_size = 128, 
  validation_split = 0.2
)
model %>% evaluate(study_admissions)
```
## Conclusion
